server:
  port: 8080

spring:
  application:
    name: black-provider
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka


