server:
  port: 9090

spring:
  application:
    name: black-consume
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&characterEncoding=utf8
    username: root
    password: root
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


remote:
  url: localhost:8080


#请求处理的超时时间
ribbon.ReadTimeout: 2000
#请求连接的超时时间
ribbon.ConnectTimeout: 2000

feign.hystrix.enabled: true
#hystrix 熔断机制
hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 2000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka


