server:
  port: 8090

spring:
  application:
    name: black-gateway

zuul:
  routes:
    api-test:
      path: /**    #api/remote/test -> black-consume/remote/test
      service-id: black-consume
  prefix: /api

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true